// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context) error
	FetchAllUser(ctx context.Context) ([]FetchAllUserRow, error)
	FindUserByEmail(ctx context.Context) (FindUserByEmailRow, error)
	InsertUser(ctx context.Context) error
	UpdateUser(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
