version: "2"
sql:
  - engine: "mysql"
    queries: "./queries/"
    schema: "../migrations/"
    gen: 
      go:
        package: "sqlc"
        out: "./"
        emit_json_tags: false #構造体にjsonタグをつけない
        emit_prepared_queries: false #プリペアードステートメントは使用しない
        emit_interface: false #queryごとにインターフェースを生成しない
        emit_exact_table_names: false #テーブル名(s抜き)がそのまま構造体としない
        emit_empty_slices: true #:manyクエリでnilの代わりに空スライスが返される