# MySQLのベースイメージを使用
FROM mysql:8.0.40-debian

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y wget unzip

# golang-migrateをインストール
RUN wget https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz && \
    tar -xvzf migrate.linux-amd64.tar.gz && \
    mv migrate /usr/local/bin/

# MySQLの設定
COPY ./app/infrastructure/db/mysql/conf.d /etc/mysql/conf.d
