// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "apiのヘルスチェックを行う。ルーティングが正常に登録されているかを確かめる。",
                "summary": "apiのヘルスチェックを行う",
                "responses": {
                    "200": {
                        "description": "Health check message",
                        "schema": {
                            "$ref": "#/definitions/presenter.SuccessResponse-health_healthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.healthResponse": {
            "type": "object",
            "properties": {
                "health_check": {
                    "type": "string"
                }
            }
        },
        "presenter.SuccessResponse-health_healthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/health.healthResponse"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TodoAPI",
	Description:      "This is TodoAPI by golang.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
